//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Repository.MenuRepository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical.Repository.MenuRepository.MenuQueries", typeof(MenuQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tblMenu(MenuName,MCat_Id,MT_Id,Price,Discount,Active,Status,AppModifiedNum) VALUES (@MenuName,@MCat_Id,@MT_Id,@Price,@Discount,1,1,0).
        /// </summary>
        internal static string InsertMenu {
            get {
                return ResourceManager.GetString("InsertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MCat_Id,MCat_Name FROM [dbo].[tblMCategory] ORDER BY MCat_Name.
        /// </summary>
        internal static string MCategoryList {
            get {
                return ResourceManager.GetString("MCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT M_Id, MenuName, MCat_Id, (SELECT MCat_Name FROM[dbo].[tblMCategory] C WHERE C.MCat_Id = M.MCat_Id) as MCat_Name, MT_Id, (SELECT T.MType_Name FROM[dbo].[tblMType] T WHERE T.MT_Id=M.MT_Id) as MType_Name, Price, Discount,Active FROM [dbo].[tblMenu] M ORDER BY M.M_Id.
        /// </summary>
        internal static string MenuList {
            get {
                return ResourceManager.GetString("MenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT M_Id, MenuName, MCat_Id, (SELECT MCat_Name FROM[dbo].[tblMCategory] C WHERE C.MCat_Id = M.MCat_Id) as MCat_Name, MT_Id, (SELECT T.MType_Name FROM[dbo].[tblMType] T WHERE T.MT_Id=M.MT_Id) as MType_Name, Price, Discount,Active FROM [dbo].[tblMenu] M where  M.M_Id=@M_Id ORDER BY M.M_Id.
        /// </summary>
        internal static string MenuListById {
            get {
                return ResourceManager.GetString("MenuListById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MT_Id, MType_Name FROM [dbo].[tblMType] WHERE MCat_Id = @MCat_Id  order by MType_Name.
        /// </summary>
        internal static string MTypeByMCatId {
            get {
                return ResourceManager.GetString("MTypeByMCatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE tblMenu SET MenuName = @MenuName, MCat_Id = @MCat_Id, MT_Id=@MT_Id ,Price = @Price,Discount = @Discount, Active=@Active WHERE (M_Id =@M_Id).
        /// </summary>
        internal static string UpdateMenu {
            get {
                return ResourceManager.GetString("UpdateMenu", resourceCulture);
            }
        }
    }
}
