//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical.Common.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string isn&apos;t provided.
        /// </summary>
        public static string ConnectionStringIsNotProvided {
            get {
                return ResourceManager.GetString("ConnectionStringIsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Name:SyncService,Errors:.
        /// </summary>
        public static string ExceptionSyncService {
            get {
                return ResourceManager.GetString("ExceptionSyncService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret failed..
        /// </summary>
        public static string FailSecret {
            get {
                return ResourceManager.GetString("FailSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized, please contact Admin to check Security Group..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is inactive. Contact your administrator to activate it..
        /// </summary>
        public static string InactiveUserContactAdmin {
            get {
                return ResourceManager.GetString("InactiveUserContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to enter this page please contact Admin.
        /// </summary>
        public static string NotAuthorizedContactAdmin {
            get {
                return ResourceManager.GetString("NotAuthorizedContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is not valid. Please enter correct OTP..
        /// </summary>
        public static string OTPTokenNotVerify {
            get {
                return ResourceManager.GetString("OTPTokenNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user profile is registered in active directory. To login please go to \&quot;Active Directory Login\&quot; page.
        /// </summary>
        public static string ProfileAlreadyExistInAD {
            get {
                return ResourceManager.GetString("ProfileAlreadyExistInAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select UserId..
        /// </summary>
        public static string RequiredUserId {
            get {
                return ResourceManager.GetString("RequiredUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests, please try after 1 min. .
        /// </summary>
        public static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized. Please login again..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not avaliable.
        /// </summary>
        public static string UserNotAvaliable {
            get {
                return ResourceManager.GetString("UserNotAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong secret code..
        /// </summary>
        public static string WrongSecret {
            get {
                return ResourceManager.GetString("WrongSecret", resourceCulture);
            }
        }
    }
}
